/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hastable;

public class App {


    public static void main(String[] args) {
    HashTable hashTable= new HashTable();
      hashTable.add("John", 300);
      hashTable.add("sanaa", 400);
      hashTable.add("Tom", 200);
      hashTable.add("Jade", 100);
      hashTable.add("Doa", 600);
      hashTable.add("Farah", 700);
      hashTable.add("Jason", 90000);
      hashTable.add("Morgan", 800);
      hashTable.add("Naim", 1000);
      hashTable.add("Qusai", 1500);
      hashTable.add("Deyaa", 10000);

        String str="Once upon a time, there was a brave princess who...";
      System.out.println("The Integer is => " + hashTable.find("Jade"));
      System.out.println("The index is => " + hashTable.getHash("Morgan"));
      System.out.println("Is contain ? => " + hashTable.contains("abrar"));
      System.out.println("Is contain ? => " + hashTable.contains("Jason"));
      System.out.println(hashTable.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York..."));
    }

}
