/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {


    public static void main(String[] args) {
      Graph graph = new Graph();
      Node node1 = graph.addNode(5);
      Node node2 = graph.addNode("Yazan");
      Node node3 = graph.addNode(101);
      System.out.println(graph.size());
      System.out.println(graph.vertices.contains(node1));
      System.out.println(graph.vertices.contains(node2));
      System.out.println(graph.vertices.contains(node3));

    }
}
