/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch11;

import ch11.stack.strucrure.Stack;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void validateBracketsTest() {
     assertTrue(Stack.validateBrackets("{}"));
    }
}
