/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testPreorder() {
      BinaryTree<Integer> binarySearchTree = new BinaryTree<>();
      binarySearchTree.insert(7);
      binarySearchTree.insert(3);
      binarySearchTree.insert(2);
      binarySearchTree.insert(4);
      binarySearchTree.insert(6);
      binarySearchTree.insert(5);

//      assertEquals("7 -> 3 -> 2 -> 4 -> 6 -> 5 ->",binarySearchTree.preorderTraversal());

    }
}
