/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testPreorder() {
      trees.BinarySearchTree<Integer> binarySearchTree = new trees.BinarySearchTree<>();
      binarySearchTree.insert(7);
      binarySearchTree.insert(3);
      binarySearchTree.insert(2);
      binarySearchTree.insert(4);
      binarySearchTree.insert(6);
      binarySearchTree.insert(5);

//      assertEquals("7 -> 3 -> 2 -> 4 -> 6 -> 5 ->",binarySearchTree.preorderTraversal());

    }
  @Test void testGetMax(){
    trees.BinarySearchTree<Integer> binarySearchTree = new trees.BinarySearchTree<>();
    binarySearchTree.insert(7);
    binarySearchTree.insert(3);
    binarySearchTree.insert(10);
    binarySearchTree.insert(4);
    binarySearchTree.insert(6);
    binarySearchTree.insert(5);
      assertEquals(10,binarySearchTree.maxData());
  }
}
