/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import data.BTNode;
import org.junit.jupiter.api.Test;
import structure.BinaryTree;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void testBFS() {
    BinaryTree binaryTree= new BinaryTree();
    binaryTree.setRoot(new BTNode("Y"));
    binaryTree.getRoot().setLeft(new BTNode("A"));
    binaryTree.getRoot().setRight(new BTNode("Z"));
    binaryTree.getRoot().getLeft().setLeft(new BTNode("A"));
    binaryTree.getRoot().getLeft().setRight(new BTNode("N"));


//  assert assertEquals("Y A Z A N ",binaryTree.bfs(),"hello");
  }
}
