/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;


  public class Main {

    public static void main(String[] args) {
      trees.BinarySearchTree<Integer> binarySearchTree = new trees.BinarySearchTree<>();
      binarySearchTree.insert(7);
      binarySearchTree.insert(3);
      binarySearchTree.insert(10);
      binarySearchTree.insert(4);
      binarySearchTree.insert(6);
      binarySearchTree.insert(5);






      System.out.println("Inorder");
      binarySearchTree.inorderTraversal();

      System.out.println("\nxxxxxxxxxxxxxxxx Preorder xxxxxxxxxxxxxxxxx");
      binarySearchTree.preorderTraversal();
      System.out.println("\nxxxxxxxxxxxxxxxx Postorder rxxxxxxxxxxxxxxxxx");
      binarySearchTree.postorderTraversal();
      System.out.println("\n");
      System.out.println(binarySearchTree.contains(10));
      System.out.println(binarySearchTree.maxData());

    }
  }

