/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;


  public class Main {

    public static void main(String[] args) {
      BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();
      binarySearchTree.insert(7);
      binarySearchTree.insert(3);
      binarySearchTree.insert(2);
      binarySearchTree.insert(4);
      binarySearchTree.insert(6);
      binarySearchTree.insert(5);


      BinarySearchTree<String> jason = new BinarySearchTree<>();
      jason.insert("J");
      jason.insert("J");
      jason.insert("A");
      jason.insert("S");
      jason.insert("O");
      jason.insert("N");

//        System.out.println("Inorder traversal");
//        binarySearchTree.inorderTraversal();


      System.out.println("Inorder traversal of Jason");
      binarySearchTree.inorderTraversal();
//      System.out.println("preorder");
//      binarySearchTree.preorderTraversal();
      System.out.println("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
      binarySearchTree.preorderTraversal();
      System.out.println("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
      binarySearchTree.postorderTraversal();

    }
  }

